/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List upload sessions
         * @description Returns a summary of every live session, most recently created first.
         */
        get: operations["list"];
        put?: never;
        /**
         * Create a new upload session
         * @description Optionally names the session via a JSON body { name }; an empty body creates an unnamed session.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stage a file into a session
         * @description Uploads one file under the given bare filename. The filename must not carry a path component, and a name may be uploaded at most once per session.
         */
        post: operations["upload"];
        /**
         * Delete all staged files from a session
         * @description Removes every staged file but keeps the (empty) session. Rejected (409) while any of the session's check runs are PENDING or RUNNING.
         */
        delete: operations["deleteAllFiles"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/files/from-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stage a file into a session by URL
         * @description The server downloads the http/https URL into the session under the given bare filename (derived from the URL path when omitted). Bounded by corej.sessions.max-download-bytes and corej.sessions.download-timeout; the JVM's global proxy system properties apply. A name may be staged at most once per session.
         */
        post: operations["uploadFromUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a check run for a session
         * @description Queues a validation run over the session's staged files; returns immediately.
         */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a check run
         * @description Pulls a queued run before it starts; signals a running run to abort cleanly.
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a session and its staged files
         * @description Rejected (409) while any of the session's check runs are PENDING or RUNNING.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Rename a session
         * @description Sets or clears (blank/null) the session's display name. Not gated by in-flight runs — it touches only metadata.
         */
        patch: operations["rename"];
        trace?: never;
    };
    "/api/sessions/{id}/files/{filename}/define-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detect the Define-XML version of a staged file
         * @description Parses the named file and reports the detected Define-XML version (1.0 / 2.0 / 2.1) from its content. Both response fields are null when the file is not a recognisable Define-XML document. The web UI calls this when a define.xml is selected to pre-fill the define-version field.
         */
        get: operations["defineVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/run-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Valid values for the run form
         * @description The selectable rule PACKAGES (short names, each with the CDISC Library standards it declares), the Define-XML version list, and the declarable CDISC Library metadata products (R4 — optional, ordered, metadata only). Plan 2 (R1/R5): a run names packages, not a standard + version, so the former standards / families / defaultFamily fields are gone.
         */
        get: operations["runOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rule ids (with descriptions) and use cases for one rule package
         * @description The CORE rule ids in the named package (each with its description, for include/exclude selection) and any Use_Case tokens it defines. Empty when no such package exists.
         */
        get: operations["rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return service name and version */
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List check runs
         * @description All runs (most recently created first), or only those of a session when sessionId is given. Each row carries its owning session's current name.
         */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a check run's status and progress
         * @description With waitSeconds > 0, long-polls up to that many seconds (capped at 60) for the run to reach a terminal state before returning the current snapshot.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run's per-rule outcomes */
        get: operations["rules_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/rules/{coreId}/definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the run-scoped source + expanded definition of one rule
         * @description { source, expanded } — source is the run's raw rule object, expanded is the synthetic generated rule that ran (null for non-generated rules). Either may be null; 404 when neither is found.
         */
        get: operations["ruleDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a succeeded run's full JSON report
         * @description The assembled v1 report document (conformance + dataset details + rules + findings) — byte-identical to the CLI's report file.
         */
        get: operations["reportXlsx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/report-v2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a succeeded run's v2 combined-finding JSON report
         * @description The v2 report: one object per finding (carrying its location plus its rows) instead of v1's per-row expansion — byte-identical to the CLI's --output-format json2 (.v2.json) file.
         */
        get: operations["reportV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a run's execution log
         * @description Files (name + size + SHA-256), the configuration, per-domain rules executed/total + findings, and any errors. Available for terminal runs that started (SUCCEEDED / FAILED / CANCELLED-after-start).
         */
        get: operations["log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/log/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a run's live execution-log lines
         * @description The run's log lines accumulated so far (INFO/WARN/DEBUG and any exception stack trace), from the given offset. Available while the run is RUNNING; poll with the returned nextFrom to stream new lines. The structured /log endpoint remains the complete view once the run is terminal.
         */
        get: operations["logLines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/log/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a run's raw execution-log file
         * @description The verbatim, pretty-printed log-<id>.json file, served as an attachment.
         */
        get: operations["logFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page through a run's findings, optionally scoped to a dataset and rule
         * @description Finding rows, optionally filtered to one file, domain and/or rule (core id). Used by the results drill-down to lazily load the findings of a specific rule in a specific dataset. Always reports the full matching total. Projected from the run's v2 combined-finding report, so each row also carries the EC-40 record key when the run resolved one; the fields are omitted entirely under the default corej.findingKeys=off.
         */
        get: operations["findings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/dataset-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a run's results grouped by file then domain
         * @description Two-level grouping: each uploaded file (with size, modification date and SHA-256) contains its domains/datasets (with label, rows, columns), each carrying that domain's rule outcomes (incl. the per-rule violation count). Findings are not embedded — fetch them on demand, scoped and paged, via the findings endpoint.
         */
        get: operations["datasetGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/conformance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run's conformance metadata */
        get: operations["conformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sizes + generation time of a run's downloadable artifacts
         * @description JSON report size, execution-log size (null if absent) and the run's finish time. The Excel report is rendered on demand, so it has no stored size.
         */
        get: operations["artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one staged file from a session
         * @description Removes the file with the given bare name. Rejected (409) while any of the session's check runs are PENDING or RUNNING.
         */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a check run and its report
         * @description Rejected (409) while the run is PENDING or RUNNING — cancel it first.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Optional parameters when creating a session */
        CreateSessionRequest: {
            /** @description Optional human-readable session name (blank/null leaves it unnamed) */
            name?: string;
        };
        /** @description Identifier of a newly created upload session */
        CreateSessionResponse: {
            /** @description Opaque session id used in subsequent file/check calls */
            sessionId?: string;
            /** @description The session's display name, or null when unnamed */
            name?: string;
        };
        /** @description Metadata of a file staged into a session */
        FileUploadResponse: {
            /** @description Owning session id */
            sessionId?: string;
            /** @description Stored (bare) file name */
            filename?: string;
            /**
             * Format: int64
             * @description Stored size in bytes
             */
            size?: number;
        };
        /** @description Stage a file into a session by URL */
        UrlUploadRequest: {
            /** @description http/https URL to download */
            url: string;
            /** @description Optional bare filename to store under */
            filename?: string;
        };
        /** @description Parameters for a check run over a session's staged files */
        CheckRunRequest: {
            /** @description TIG use case (optional) */
            useCase?: string;
            /** @description Name of an uploaded define.xml to use as metadata overlay (optional) */
            defineXmlFilename?: string;
            /**
             * @deprecated
             * @description DEPRECATED — use 'datasetFilter' instead. Names of uploaded files to load as reference libraries (optional). A dataset the filter does not match is still loaded as reference data — visible to rules, never validated — which is what this field was for. Only formats a library supplier can open are accepted; any other format is rejected with 400 naming the file, its format and the supported list.
             */
            referenceDataFilenames?: string[];
            /** @description Explicit Define-XML version; null reads it from the library */
            defineVersion?: string;
            /** @description Include filter of CORE rule ids; when non-empty, only these rules run */
            includeRules?: string[];
            /** @description Exclude filter of CORE rule ids; when non-empty, all but these rules run */
            excludeRules?: string[];
            /** @description Names of uploaded rule-package files to load in addition to bundled rules */
            rulesFilenames?: string[];
            /** @description Restrict validation to these dataset/domain names; empty validates all */
            datasetFilter?: string[];
            /**
             * Format: int32
             * @description Rule worker threads per dataset (>= 1); default 1
             */
            ruleThreads?: number;
            /**
             * Format: int32
             * @description Max findings to materialise per rule (per dataset); additional violations are counted but not listed. Null (the default) uses the service default (corej.engine.max-errors-per-rule / MAX_ERRORS_PER_RULE); <= 0 means unlimited.
             */
            maxErrorsPerRule?: number;
            /** @description Ordered CDISC Library products consulted for metadata, highest precedence first (e.g. adam/adamig-1-3; a bare product id is accepted when unambiguous against the server's metadata cache). Selects METADATA only - rules are selected by 'rulesPackages'. Null or empty uses the standards the selected rule packages declare — and is therefore REQUIRED (400) when rules are selected only by 'rulesFilenames', since an uploaded rules file declares no standard. */
            metadataProducts?: string[];
            /**
             * @description Weakest check level to evaluate: Reject, Error, Warning or Info. A rule's declared levels below it are not evaluated, and a rule with no level at or above it is skipped with a stated reason rather than passing silently. Null (the default) means Warning, so Reject+Error+Warning evaluate and Info does not. This is a RUN option only — no rule package and no rule may carry one. Notice is NOT a threshold — it is a report-only kind outside the ladder, authored by no rule.
             * @example Warning
             * @enum {string}
             */
            severityThreshold?: "Reject" | "Error" | "Warning" | "Info";
            /** @description Rule packages to run, by short name (e.g. cdisc-adamig-1-3 for rules-cdisc-adamig-1-3.json). REQUIRED unless 'rulesFilenames' names uploaded rule files instead; the two are unioned. The selected packages declare the CDISC Library standards the run resolves metadata against, which is why this replaced the removed 'standard' and 'version' fields. */
            rulesPackages: string[];
        };
        /** @description Identifier of a newly started check run */
        StartCheckResponse: {
            /** @description Opaque check-run id used to poll status / findings */
            checkRunId?: string;
        };
        /** @description New session name (blank/null clears it) */
        RenameSessionRequest: {
            /** @description Display name; blank/null leaves the session unnamed */
            name?: string;
        };
        /** @description A file staged into a session */
        SessionFile: {
            /** @description Stored (bare) file name */
            filename?: string;
            /**
             * Format: int64
             * @description Stored size in bytes
             */
            sizeBytes?: number;
            /** @description Upload time (ISO-8601, UTC) */
            uploadedAt?: string;
        };
        /** @description Summary of an upload session */
        SessionSummary: {
            /** @description Session id */
            sessionId?: string;
            /** @description Display name, or null when unnamed */
            name?: string;
            /** @description Creation time (ISO-8601) */
            createdAt?: string;
            /**
             * Format: int32
             * @description Number of files staged in the session
             */
            fileCount?: number;
            /** @description The files staged in the session */
            files?: components["schemas"]["SessionFile"][];
        };
        /** @description Detected Define-XML version of a staged file */
        DefineVersionResponse: {
            /**
             * @description Short version label, e.g. 2.1; null if undeterminable
             * @example 2.1
             */
            version?: string;
            /**
             * @description def:DefineVersion value, e.g. 2.1.0; matches the run form's define-version options; null if undeterminable
             * @example 2.1.0
             */
            defineVersion?: string;
        };
        /** @description A selectable rule package */
        PackageOption: {
            /** @description Short name to pass as rulesPackages, e.g. cdisc-sdtmig-3-4 */
            name?: string;
            /** @description Rule family (display only) */
            family?: string;
            /** @description Standard display name (display only) */
            standard?: string;
            /** @description Version display form (display only) */
            version?: string;
            /**
             * Format: int32
             * @description Number of rules in the package
             */
            ruleCount?: number;
            /** @description CDISC Library product ids this package declares */
            standards?: string[];
        };
        /** @description Valid values for the run form */
        RunOptions: {
            /** @description Selectable rule packages, sorted by short name */
            packages?: components["schemas"]["PackageOption"][];
            /** @description Define-XML version options */
            defineVersions?: string[];
            /** @description Declarable CDISC Library metadata products, as <group>/<product> */
            metadataProducts?: string[];
        };
        /** @description A CORE rule id and its description */
        RuleOption: {
            /** @description CORE rule id */
            id?: string;
            /** @description Rule description (may be null) */
            description?: string;
        };
        /** @description Rules and use cases for a standard + version */
        RuleOptions: {
            /** @description CORE rules in the matching pack (id + description) */
            rules?: components["schemas"]["RuleOption"][];
            /** @description Use_Case tokens defined by the pack */
            useCases?: string[];
        };
        Info: {
            service?: string;
            version?: string;
        };
        /** @description Status and progress of a check run */
        CheckStatusResponse: {
            /** @description Check-run id */
            checkRunId?: string;
            /** @description Owning session id */
            sessionId?: string;
            /** @description Owning session's display name, or null when unnamed/deleted */
            sessionName?: string;
            /**
             * @description Lifecycle state
             * @enum {string}
             */
            status?: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /**
             * Format: int32
             * @description Target datasets discovered (-1 until known)
             */
            totalDatasets?: number;
            /**
             * Format: int32
             * @description Datasets completed
             */
            processedDatasets?: number;
            /**
             * Format: int32
             * @description Rules executed so far
             */
            rulesExecuted?: number;
            /**
             * Format: int32
             * @description Findings: the authoritative total once SUCCEEDED; while RUNNING, a running tally over the datasets finished so far; null otherwise
             */
            findingCount?: number;
            /** @description Failure detail (only when FAILED) */
            message?: string;
            /** @description Creation time (ISO-8601) */
            createdAt?: string;
            /** @description Start time (ISO-8601), null while PENDING */
            startedAt?: string;
            /** @description Completion time (ISO-8601), null until terminal */
            finishedAt?: string;
        };
        /** @description A rule's outcome in the run */
        RuleReportRow: {
            /** @description CORE rule id */
            coreId?: string;
            /** @description Rule report version */
            version?: string;
            /** @description CDISC rule id(s) */
            cdiscRuleId?: string;
            /** @description FDA rule id(s) */
            fdaRuleId?: string;
            /** @description Rule message */
            message?: string;
            /** @description Outcome status (e.g. SUCCESS, SOME_ISSUES, ERROR) */
            status?: string;
        };
        JsonNode: {
            empty?: boolean;
            array?: boolean;
            null?: boolean;
            object?: boolean;
            float?: boolean;
            container?: boolean;
            string?: boolean;
            missingNode?: boolean;
            valueNode?: boolean;
            pojo?: boolean;
            number?: boolean;
            floatingPointNumber?: boolean;
            short?: boolean;
            int?: boolean;
            long?: boolean;
            double?: boolean;
            bigDecimal?: boolean;
            bigInteger?: boolean;
            /** @deprecated */
            textual?: boolean;
            boolean?: boolean;
            binary?: boolean;
            /** @enum {string} */
            nodeType?: "ARRAY" | "BINARY" | "BOOLEAN" | "MISSING" | "NULL" | "NUMBER" | "OBJECT" | "POJO" | "STRING";
            integralNumber?: boolean;
            embeddedValue?: boolean;
        };
        /** @description Execution stats for one validated domain */
        DomainLogEntry: {
            /** @description Domain / dataset name */
            domain?: string;
            /** @description Source file name */
            fileName?: string;
            /**
             * Format: int32
             * @description Rules executed for this domain (X)
             */
            rulesExecuted?: number;
            /**
             * Format: int32
             * @description Total rules available for the run (Y)
             */
            rulesTotal?: number;
            /**
             * Format: int32
             * @description Findings attributed to this domain
             */
            findings?: number;
            /**
             * Format: int64
             * @description Dataset wall-clock validation time in ms (-1 = not measured)
             */
            runtimeMillis?: number;
            /** @description Errors encountered for this domain */
            errors?: components["schemas"]["RuleErrorEntry"][];
            /** @description Per-rule outcome of every rule run against this domain */
            ruleExecutions?: components["schemas"]["RuleExecutionEntry"][];
        };
        /** @description An uploaded file's name, size and hash */
        FileManifestEntry: {
            /** @description File name */
            filename?: string;
            /**
             * Format: int64
             * @description Size in bytes
             */
            sizeBytes?: number;
            /** @description SHA-256 hex digest */
            sha256?: string;
        };
        /** @description An error and the rule that produced it */
        RuleErrorEntry: {
            /** @description Rule id (or synthetic load-error id) */
            ruleId?: string;
            /** @description Error detail */
            message?: string;
        };
        /** @description One rule's outcome against a dataset */
        RuleExecutionEntry: {
            /** @description Rule CORE id (expanded id for generated rules) */
            coreId?: string;
            /** @description Engine synthetic rule id */
            generatedId?: string;
            /** @description EXECUTED | SKIPPED | ERROR */
            status?: string;
            /**
             * Format: int32
             * @description Violations reported for this dataset
             */
            violations?: number;
            /**
             * Format: int64
             * @description Execution runtime in ms for this rule on this dataset (-1 = not measured)
             */
            runtimeMillis?: number;
            /** @description Variable a generated rule was expanded for (null otherwise) */
            expandedFor?: string;
            /** @description Why the rule was not executed (null when EXECUTED) */
            notExecutedReason?: string;
            /** @description Rule description (null when the rule carries none) */
            description?: string;
            /** @description Rule executability in title-case display form (null when none) */
            executability?: string;
        };
        /** @description A run's execution log */
        RunLog: {
            /** @description Run id */
            runId?: string;
            /** @description Owning session id */
            sessionId?: string;
            /** @description Terminal status (SUCCEEDED | FAILED | CANCELLED) */
            status?: string;
            /** @description Run creation timestamp (ISO-8601) */
            createdAt?: string;
            /** @description Run start timestamp (ISO-8601) */
            startedAt?: string;
            /** @description Run finish timestamp (ISO-8601) */
            finishedAt?: string;
            /**
             * Format: double
             * @description Total runtime in seconds (null if the run did not complete)
             */
            totalRuntimeSeconds?: number;
            /** @description The configuration the run was started with */
            configuration?: components["schemas"]["CheckRunRequest"];
            /** @description Manifest of the session's uploaded files */
            files?: components["schemas"]["FileManifestEntry"][];
            /** @description Per-domain execution summary */
            domains?: components["schemas"]["DomainLogEntry"][];
            /**
             * Format: int32
             * @description Total findings across all domains (null if the run did not complete)
             */
            totalFindings?: number;
            /** @description Failure detail when the run failed */
            failureMessage?: string;
            /** @description Run-relevant engine log lines (level-prefixed), in order */
            logLines?: string[];
        };
        /** @description A page of a run's live log lines */
        LiveLogResponse: {
            /** @description Log lines from the requested offset, in order */
            lines?: string[];
            /**
             * Format: int32
             * @description Cursor to pass as 'from' on the next poll
             */
            nextFrom?: number;
            /** @description Whether the run has reached a terminal state */
            terminal?: boolean;
        };
        /** @description A single finding row */
        FindingRow: {
            /** @description CORE rule id */
            coreId?: string;
            /** @description Dataset / domain label */
            dataset?: string;
            /** @description USUBJID of the affected record, if any */
            usubjid?: string;
            /**
             * Format: int32
             * @description 1-based row number in the dataset, or null when not row-scoped
             */
            row?: number;
            /** @description Sequence number (e.g. AESEQ), if any */
            seq?: string;
            /** @description Rule executability status */
            executability?: string;
            /** @description Finding message */
            message?: string;
            /** @description Names of the variables reported for this row */
            variables?: string[];
            /** @description Values of those variables for this row (positional) */
            values?: string[];
            /** @description Domain / dataset name (disambiguates findings sharing a file) */
            domain?: string;
            /** @description Ordered record-key column names identifying this row, when resolved */
            keyVariables?: string[];
            /** @description Record-key values for this row, keyed by column name */
            keys?: {
                [key: string]: string;
            };
            /** @description Which tier produced the record key: DEFINE_KEY, STRUCTURAL, NATURAL or SPONSOR_ID */
            keySource?: string;
        };
        /** @description A page of finding rows */
        FindingsPage: {
            /**
             * Format: int32
             * @description Total finding rows for the run
             */
            total?: number;
            /**
             * Format: int32
             * @description Index of the first returned row
             */
            firstIndex?: number;
            /**
             * Format: int32
             * @description Number of rows in this page
             */
            count?: number;
            /** @description The finding rows in this page */
            items?: components["schemas"]["FindingRow"][];
        };
        /** @description One domain (dataset) within a file */
        DomainGroup: {
            /** @description Domain / dataset name */
            domain?: string;
            /** @description Dataset label */
            label?: string;
            /**
             * Format: int64
             * @description Row count
             */
            rows?: number;
            /**
             * Format: int32
             * @description Column (variable) count
             */
            columns?: number;
            /**
             * Format: int64
             * @description Dataset wall-clock validation time in ms (-1 = not measured)
             */
            runtimeMillis?: number;
            /** @description Per-rule outcomes against this domain */
            rules?: components["schemas"]["RuleExecutionEntry"][];
        };
        /** @description One file and the domains it contains */
        FileGroup: {
            /** @description Stored file name */
            fileName?: string;
            /**
             * Format: int64
             * @description File size in bytes
             */
            sizeBytes?: number;
            /** @description SHA-256 hex digest */
            sha256?: string;
            /** @description Last-modification timestamp */
            modificationDate?: string;
            /** @description Domains (datasets) contained in this file */
            domains?: components["schemas"]["DomainGroup"][];
        };
        /** @description Conformance metadata for a run */
        ConformanceResponse: {
            /** @description CDISC standard (upper-cased), e.g. SDTMIG */
            standard?: string;
            /** @description Substandard, if any */
            substandard?: string;
            /** @description Standard version display form, e.g. V3.4 */
            version?: string;
            /** @description TIG use case, if any */
            tigUseCase?: string;
            /** @description Controlled-terminology version(s) */
            ctVersion?: string;
            /** @description Define-XML version, if known */
            defineXmlVersion?: string;
            /** @description CORE engine version, if stamped */
            coreEngineVersion?: string;
            /** @description Total runtime, e.g. "12.34 seconds" */
            totalRuntime?: string;
            /** @description Per-rule issue limit, or "None" */
            issueLimitPerRule?: string;
            /** @description Per-dataset issue limit flag */
            issueLimitPerDataset?: string;
            /** @description Report generation timestamp (UTC, ISO-8601) */
            reportGeneration?: string;
            /** @description Library degradation note — present only when the CDISC Library could not be consulted for the run */
            libraryMetadataBasis?: string;
            /** @description External-dictionary degradation note — present only when some dictionary rule in the run could not be answered; names what loaded (with versions), what did not and why, and the answerable count */
            dictionaryBasis?: string;
        };
        /** @description Downloadable artifacts of a run */
        RunArtifacts: {
            /**
             * Format: int64
             * @description JSON report size in bytes (null if absent)
             */
            reportBytes?: number;
            /**
             * Format: int64
             * @description v2 combined-finding JSON report size in bytes (null if absent)
             */
            reportV2Bytes?: number;
            /**
             * Format: int64
             * @description Pre-rendered XLSX report size in bytes (null if absent)
             */
            reportXlsxBytes?: number;
            /**
             * Format: int64
             * @description Execution-log size in bytes (null if absent)
             */
            logBytes?: number;
            /** @description When the run finished / the artifacts were generated (ISO-8601) */
            generatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Invalid session name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload: {
        parameters: {
            query: {
                filename: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File staged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Filename missing or carries a path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Filename already present */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAllFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All files deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session has in-flight runs */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadFromUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlUploadRequest"];
            };
        };
        responses: {
            /** @description File staged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Malformed/disallowed URL or invalid filename */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Filename already present */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Download exceeds the size cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRunRequest"];
            };
        };
        responses: {
            /** @description Run queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StartCheckResponse"];
                };
            };
            /** @description Invalid request / unknown referenced file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session has in-flight runs */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Updated session summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionSummary"];
                };
            };
            /** @description Invalid session name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    defineVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detected version (fields null if undeterminable) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DefineVersionResponse"];
                };
            };
            /** @description Filename carries a path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session or file */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunOptions"];
                };
            };
        };
    };
    rules: {
        parameters: {
            query: {
                package: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleOptions"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Info"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckStatusResponse"][];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: {
                waitSeconds?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckStatusResponse"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rules_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rules report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleReportRow"][];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ruleDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                coreId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rule definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonNode"];
                };
            };
            /** @description Unknown run or no definition */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reportXlsx: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed / not yet complete */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reportV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full v2 report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed / not yet complete */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The execution log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunLog"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No execution log for this run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logLines: {
        parameters: {
            query?: {
                from?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The live log lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LiveLogResponse"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The raw log file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No execution log for this run */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findings: {
        parameters: {
            query?: {
                file?: string;
                domain?: string;
                coreId?: string;
                firstIndex?: number;
                count?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of finding rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FindingsPage"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    datasetGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The grouped results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FileGroup"][];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conformance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conformance block */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConformanceResponse"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    artifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artifact sizes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunArtifacts"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run did not succeed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Filename carries a path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session or file */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session has in-flight runs */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run still in flight */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
